services:
  db:
    image: bitnamilegacy/postgresql:15
    container_name: cinema_db
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password

      POSTGRESQL_USERNAME: cinema_user
      POSTGRESQL_PASSWORD: cinema_password
      POSTGRESQL_DATABASE: cinema_db

      POSTGRESQL_POSTGRES_PASSWORD: super_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_primary_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema_user -d cinema_db -h 127.0.0.1 -p 5432"]
      interval: 3s
      timeout: 5s
      retries: 20

  db_replica:
    image: bitnamilegacy/postgresql:15
    container_name: cinema_db_replica
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: db
      POSTGRESQL_MASTER_PORT_NUMBER: 5432

      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password

      POSTGRESQL_PASSWORD: cinema_password
      POSTGRESQL_POSTGRES_PASSWORD: super_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_replica_data:/bitnami/postgresql
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema_user -d cinema_db -h 127.0.0.1 -p 5432"]
      interval: 3s
      timeout: 5s
      retries: 20

  backend:
    build: .
    container_name: cinema_backend
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      db_replica:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=cinema_db
      - DB_USER=cinema_user
      - DB_PASS=cinema_password
      - DB_PORT=5432

      - DB_REPLICA_HOST=db_replica
      - DB_REPLICA_PORT=5432

volumes:
  postgres_primary_data:
  postgres_replica_data: