services:
  db:
    image: bitnamilegacy/postgresql:15
    container_name: cinema_db
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: ${DB_REPL_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${DB_REPL_PASSWORD}

      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}

      POSTGRESQL_POSTGRES_PASSWORD: ${DB_SUPER_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_primary_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h 127.0.0.1 -p 5432"]
      interval: 3s
      timeout: 5s
      retries: 20

  db_replica:
    image: bitnamilegacy/postgresql:15
    container_name: cinema_db_replica
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: db
      POSTGRESQL_MASTER_PORT_NUMBER: 5432

      POSTGRESQL_REPLICATION_USER: ${DB_REPL_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${DB_REPL_PASSWORD}

      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${DB_SUPER_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_replica_data:/bitnami/postgresql
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h 127.0.0.1 -p 5432"]
      interval: 3s
      timeout: 5s
      retries: 20

  shard_0:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["5440:5432"]

  shard_1:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["5441:5432"]

  shard_2:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["5442:5432"]

  shard_3:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["5443:5432"]

  backend:
    build: .
    container_name: cinema_backend
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      db_replica:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_PORT=5432

      - DB_REPLICA_HOST=db_replica
      - DB_REPLICA_PORT=5432

volumes:
  postgres_primary_data:
  postgres_replica_data: